spring:
  application:
    name: taco-cloud
  datasource:
    generate-unique-name: false
    name: tacocloud
  cassandra:
    keyspace-name: tacocloud
    local-datacenter: datacenter1
    schema-action: recreate